#!/usr/bin/env python
"""Script template for Alembic migrations."""
from __future__ import with_statement
from alembic import op
import sqlalchemy as sa

revision = '8c2fcdcf5b5c'
down_revision = '3ad436e18303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
